// <auto-generated />
using System;
using Infrastructure.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace WebApi.Migrations
{
    [DbContext(typeof(AdventistContext))]
    partial class AdventistContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Infrastructure.Repositories.FeeNoRepo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("FeeNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("FeeNos");
                });

            modelBuilder.Entity("Infrastructure.Repositories.HealthItemRepo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<DateTimeOffset>("CREATE_DATE")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CREATE_ID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CREATE_NAME")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("MODIFY_DATE")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("MODIFY_ID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MODIFY_NAME")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VS_CARE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VS_MEMO")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VS_OTHER_MEMO")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VS_PART")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VS_REASON")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VS_RECORD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VS_TYPE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("Vs_IdRepoId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("Vs_IdRepoId");

                    b.ToTable("HealthItem");
                });

            modelBuilder.Entity("Infrastructure.Repositories.Vs_IdRepo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<long?>("FeeNoRepoId")
                        .HasColumnType("bigint");

                    b.Property<string>("VS_ID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FeeNoRepoId");

                    b.ToTable("Vs_Ids");
                });

            modelBuilder.Entity("Infrastructure.Repositories.HealthItemRepo", b =>
                {
                    b.HasOne("Infrastructure.Repositories.Vs_IdRepo", null)
                        .WithMany("HealthItemRepos")
                        .HasForeignKey("Vs_IdRepoId");
                });

            modelBuilder.Entity("Infrastructure.Repositories.Vs_IdRepo", b =>
                {
                    b.HasOne("Infrastructure.Repositories.FeeNoRepo", null)
                        .WithMany("Vs_IdRepos")
                        .HasForeignKey("FeeNoRepoId");
                });

            modelBuilder.Entity("Infrastructure.Repositories.FeeNoRepo", b =>
                {
                    b.Navigation("Vs_IdRepos");
                });

            modelBuilder.Entity("Infrastructure.Repositories.Vs_IdRepo", b =>
                {
                    b.Navigation("HealthItemRepos");
                });
#pragma warning restore 612, 618
        }
    }
}
